language: node_js
node_js:
  - "6.0"
env:
  - APP_VERSION=default
before_install:
  - echo "before_install"
install:
  - echo "install"
before_script:
  - echo "before_script"
script:
  - echo "script"
after_success:
  - echo "after_success"