language: node_js
node_js:
  - "6.0"
env:
  - APP_VERSION=default
before_install:
  - npm run clean
install:
  - npm install
before_script:
  - npm run build
script:
  - npm version patch
after_success:
  - npm publish