language: node_js
node_js:
  - "6.0"
env:
  - APP_VERSION=default
deploy:
  provider: npm
  email: h-@live.se
  api_key:
    secure: NPM_API_KEY
  on:
    repo: hamedasemi/webrew
    branch: mainline
before_install:
  - npm run clean
install:
  - npm install
before_script:
  - npm run build
script:
  - echo 'script'
after_success:
  - npm publish